version: '3.8'

services:
  kerm-session:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./sessions:/app/sessions  # pour persister les sessions
    environment:
      - NODE_ENV=production
